#define CREATE         1
#define TABLE          2
#define INSERT         3
#define INTO           4
#define SELECT         5
#define FROM           6
#define WHERE          7
#define PRIMARY        8
#define FOREIGN        9
#define KEY            10
#define DEFAULT        11
#define NOT            12
#define TOKEN_NULL     13
#define AND            14
#define OR             15
#define COMPARATOR     16
#define REFERENCES     17
#define ORDER          18
#define BY             19
#define DELETE         20
#define DATATYPE       21
#define VALUES         22
#define AUTO_INCREMENT 23
#define ASC            24
#define DESC           25
#define UNIQUE         26
#define IN             27
#define TRUE           28
#define FALSE          29
#define DISTINCT       30
#define SET            31
#define DROP           32
#define ALTER          33
#define ADD            34
#define COLUMN         35
#define ALL_COLUMN     36
#define BRACKET_OPEN   37
#define BRACKET_CLOSE  38
#define IDENTIFIER     39
#define INT_LITERAL    40
#define STRING_LITERAL 41
#define SPACE          42
#define SEMICOLON      43
