#define CREATE 1
#define TABLE 2
#define INSERT 3  
#define INTO 4
#define SELECT 5  
#define FROM 6
#define WHERE 7  
#define PRIMARY 8  
#define FOREIGN 9  
#define KEY 10  
#define DEFAULT 11   
#define NOT 12  
#define TOKEN_NULL 13   
#define AND 14  
#define OR 15  
#define NEQ 16  
#define GEQ 17  
#define LEQ 18  
#define GT 19  
#define LT 20  
#define REFERENCES 21  
#define ORDER 22  
#define BY 23  
#define DELETE 24  
#define INT 25  
#define DOUBLE 26  
#define CHAR 27  
#define VARCHAR 28   
#define BIT 29  
#define TEXT 30  
#define VALUES 31  
#define AUTO_INCREMENT 32   
#define ASC 33  
#define DESC 34  
#define UNIQUE 35  
#define IN 36  
#define TRUE 37  
#define FALSE 38  
#define DISTINCT 39   
#define SET 40 
#define DROP 41 
#define ALTER 42 
#define ADD 43
#define COLUMN 44
#define ALL_COLUMN 45
#define IDENTIFIER 46   
#define INT_LITERAL 47  